=== sproctor/dirtywater/dirtywater/data/races/race.dtd
<!ELEMENT race (body-part)>
<!ATTLIST race
	id CDATA #REQUIRED>
	name CDATA #REQUIRED>
<!ELEMENT body-part (body-part*)>
<!ATTLIST body-part
	type CDATA #REQUIRED
	side CDATA #IMPLIED>

=== sproctor/dirtywater/src/data/races/human.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE race SYSTEM "race.dtd">
<race id="1" name="human">
	<body-part type="head">
		<body-part type="torso">
			<body-part type="arm" side="left">
				<body-part type="hand" side="left" />
			</body-part>
			<body-part type="arm" side="right">
				<body-part type="hand" side="right" />
			</body-part>
			<body-part type="leg" side="left">
				<body-part type="foot" side="left" />
			</body-part>
			<body-part type="leg" side="right">
				<body-part type="foot" side="right" />
			</body-part>
		</body-part>
	</body-part>
</race>
